name: test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create dot env file
        shell: bash
        run: |
          touch .env
          echo "CODIC_API_KEY=${{ secrets.CODIC_API_KEY }}" >> .env
          echo "PROJECT_ID=${{ secrets.PROJECT_ID }}" >> .env
          echo "PROJECT_NAME=${{ secrets.PROJECT_NAME }}" >> .env

      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17.3"

      - name: Run go vet
        run: go vet -v ./...

      - name: Run go test
        run: go test -v -race ./...
